FROM node:18-alpine

WORKDIR /app

COPY app/package.json /app/

RUN npm install --loglevel verbose  --legacy-peer-deps

# RUN mkdir -p /app/node_modules/.cache; chmod -R 777 /app/node_modules/.cache
COPY app/ /app/

ENV NODE_OPTIONS=--max_old_space_size=1024

# ENTRYPOINT ["/bin/sh", "-c"]

# CMD ["npm start"]
